[package]
name = "hello-world"
version = "0.1.0"
nanvix-version = "0.12.410"

[builds]
[builds.matrix]
platforms = ["hyperlight", "microvm"]
modes = ["standalone", "single-process", "multi-process"]
memory = ["128mb"]

[test.standalone]
targets = ["test-smoke", "test-integration"]
