# Copyright(c) The Maintainers of Nanvix.
# Licensed under the MIT License.

"""Lockfile data model, serialization, and release-asset download.

Defines the ``Lockfile`` dataclass that captures the fully resolved
dependency graph with pinned asset URLs.  Provides ``write_lockfile()``
to serialize a lockfile to TOML and ``read_lockfile()`` to parse it back.
``download_lockfile_asset()`` fetches a shallow ``nanvix.lock`` from a
GitHub release for transitive dependency discovery.
"""

from __future__ import annotations

import hashlib
import importlib.metadata
import time
import tomllib
import urllib.error
import urllib.request
from dataclasses import dataclass, field
from pathlib import Path
from typing import cast

import tomli_w

from nanvix_zutil import log
from nanvix_zutil.buildroot import Ref, RefKind
from nanvix_zutil.exitcodes import (
    EXIT_INVALID_ARGS,
    EXIT_MISSING_DEP,
    EXIT_NETWORK_ERROR,
)

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

_LOCKFILE_HEADER = "# nanvix.lock — auto-generated by nanvix_zutil. DO NOT EDIT."
_LOCKFILE_ASSET_NAME = "nanvix.lock"

_MAX_RETRIES = 3
_BACKOFF_BASE = 2.0
_HTTP_TIMEOUT = 30.0


# ---------------------------------------------------------------------------
# Data model
# ---------------------------------------------------------------------------


@dataclass
class ResolvedAsset:
    """A single downloadable release artifact.

    Attributes:
        name: File name of the asset
            (e.g. ``"zlib-hyperlight-multi-process-128mb.tar.bz2"``).
        url: Full ``browser_download_url`` from the GitHub API.
    """

    name: str
    url: str


@dataclass
class ResolvedPackage:
    """A fully resolved dependency in the lockfile.

    Attributes:
        name: Short package name (e.g. ``"zlib"``).
        repo: GitHub repository in ``owner/name`` format.
        kind: Either ``"sysroot"`` or ``"dependency"``.
        ref: The original version reference from the manifest.
        resolved_tag: Actual ``tag_name`` from the resolved release.
        resolved_commitish: Full ``target_commitish`` SHA from the release.
        release_id: GitHub release ID.
        dependencies: Names of packages this package depends on.
        assets: List of downloadable ``.tar.bz2`` assets.
        transitive: ``True`` if this package was discovered transitively.
        required_by: Names of packages that pulled this one in.
    """

    name: str
    repo: str
    kind: str
    ref: Ref
    resolved_tag: str
    resolved_commitish: str
    release_id: int
    dependencies: list[str] = field(default_factory=list)
    assets: list[ResolvedAsset] = field(default_factory=list)
    transitive: bool = False
    required_by: list[str] = field(default_factory=list)


@dataclass
class LockfileMetadata:
    """Lockfile header metadata.

    Attributes:
        manifest_hash: SHA-256 hash of the ``nanvix.toml`` file
            (e.g. ``"sha256:a1b2c3d4..."``).
        nanvix_zutil_version: Version of ``nanvix-zutil`` that
            generated this lockfile.
    """

    manifest_hash: str
    nanvix_zutil_version: str


@dataclass
class Lockfile:
    """Complete resolved dependency graph.

    Attributes:
        metadata: Lockfile header metadata.
        packages: Ordered list of resolved packages.
    """

    metadata: LockfileMetadata
    packages: list[ResolvedPackage] = field(default_factory=list)


# ---------------------------------------------------------------------------
# Version helper
# ---------------------------------------------------------------------------


def get_zutil_version() -> str:
    """Return the installed ``nanvix-zutil`` version string.

    Returns:
        Version string (e.g. ``"0.2.2"``), or ``"unknown"`` if the
        package metadata is unavailable.
    """
    try:
        return importlib.metadata.version("nanvix-zutil")
    except importlib.metadata.PackageNotFoundError:
        return "unknown"


# ---------------------------------------------------------------------------
# Write
# ---------------------------------------------------------------------------


def write_lockfile(lockfile: Lockfile, path: Path) -> None:
    """Serialize a :class:`Lockfile` to TOML and write it to *path*.

    The output starts with the standard lockfile header comment and
    includes a blank line before each ``[[package]]`` block for
    readability.

    Args:
        lockfile: The lockfile to serialize.
        path: Destination file path.
    """
    path.parent.mkdir(parents=True, exist_ok=True)

    lines: list[str] = [_LOCKFILE_HEADER, ""]

    # [metadata]
    meta_dict: dict[str, str] = {
        "manifest-hash": lockfile.metadata.manifest_hash,
        "nanvix-zutil-version": lockfile.metadata.nanvix_zutil_version,
    }
    lines.append(tomli_w.dumps({"metadata": meta_dict}).rstrip())
    lines.append("")

    # [[package]] blocks
    for pkg in lockfile.packages:
        pkg_dict: dict[str, object] = {
            "name": pkg.name,
            "repo": pkg.repo,
            "kind": pkg.kind,
            "ref-kind": pkg.ref.kind.value,
            "ref-value": pkg.ref.value,
            "resolved-tag": pkg.resolved_tag,
            "resolved-commitish": pkg.resolved_commitish,
            "release-id": pkg.release_id,
            "dependencies": pkg.dependencies,
        }
        if pkg.transitive:
            pkg_dict["transitive"] = True
        if pkg.required_by:
            pkg_dict["required-by"] = pkg.required_by

        # Build assets as list of inline tables
        asset_dicts: list[dict[str, str]] = [
            {"name": a.name, "url": a.url} for a in pkg.assets
        ]

        lines.append("")
        lines.append("[[package]]")
        # Serialize the scalar fields
        for key, value in pkg_dict.items():
            lines.append(tomli_w.dumps({key: value}).rstrip())

        # Serialize assets as [[package.assets]] sub-tables
        for asset_dict in asset_dicts:
            lines.append("")
            lines.append("[[package.assets]]")
            lines.append(tomli_w.dumps({"name": asset_dict["name"]}).rstrip())
            lines.append(tomli_w.dumps({"url": asset_dict["url"]}).rstrip())

    lines.append("")
    path.write_text("\n".join(lines))


# ---------------------------------------------------------------------------
# Read
# ---------------------------------------------------------------------------


def read_lockfile(path: Path) -> Lockfile:
    """Parse a TOML lockfile into a :class:`Lockfile` dataclass.

    Args:
        path: Path to the ``nanvix.lock`` file.

    Returns:
        The parsed :class:`Lockfile`.

    Raises:
        SystemExit: With exit code ``3`` if the file does not exist, or
            exit code ``2`` if the file is malformed.
    """
    if not path.is_file():
        log.fatal(
            f"Lockfile not found: {path}",
            code=EXIT_MISSING_DEP,
            hint="Run `./z lock` to generate a lockfile.",
        )

    raw_bytes = path.read_bytes()
    try:
        data: dict[str, object] = tomllib.loads(raw_bytes.decode("utf-8"))
    except tomllib.TOMLDecodeError as exc:
        log.fatal(
            f"Malformed lockfile {path}: {exc}",
            code=EXIT_INVALID_ARGS,
        )

    # Parse metadata
    raw_meta: object = data.get("metadata")
    if not isinstance(raw_meta, dict):
        log.fatal(
            f"Lockfile {path}: missing or invalid [metadata] section",
            code=EXIT_INVALID_ARGS,
        )
    meta = cast("dict[str, object]", raw_meta)

    manifest_hash = meta.get("manifest-hash")
    if not isinstance(manifest_hash, str):
        log.fatal(
            f"Lockfile {path}: missing or invalid 'manifest-hash'",
            code=EXIT_INVALID_ARGS,
        )

    zutil_version = meta.get("nanvix-zutil-version")
    if not isinstance(zutil_version, str):
        log.fatal(
            f"Lockfile {path}: missing or invalid 'nanvix-zutil-version'",
            code=EXIT_INVALID_ARGS,
        )

    metadata = LockfileMetadata(
        manifest_hash=manifest_hash,
        nanvix_zutil_version=zutil_version,
    )

    # Parse packages
    raw_packages: object = data.get("package", [])
    if not isinstance(raw_packages, list):
        log.fatal(
            f"Lockfile {path}: 'package' must be an array of tables",
            code=EXIT_INVALID_ARGS,
        )

    packages: list[ResolvedPackage] = []
    for raw_pkg_item in cast("list[object]", raw_packages):
        if not isinstance(raw_pkg_item, dict):
            log.fatal(
                f"Lockfile {path}: each [[package]] must be a table",
                code=EXIT_INVALID_ARGS,
            )
        pkg_data = cast("dict[str, object]", raw_pkg_item)
        packages.append(_parse_package(pkg_data, path))

    return Lockfile(metadata=metadata, packages=packages)


def _parse_package(data: dict[str, object], path: Path) -> ResolvedPackage:
    """Parse a single ``[[package]]`` entry.

    Args:
        data: The parsed TOML table for one package.
        path: Lockfile path (for error messages).

    Returns:
        A :class:`ResolvedPackage`.
    """
    name = data.get("name")
    if not isinstance(name, str):
        log.fatal(f"Lockfile {path}: package missing 'name'", code=EXIT_INVALID_ARGS)

    repo = data.get("repo")
    if not isinstance(repo, str):
        log.fatal(
            f"Lockfile {path}: package '{name}' missing 'repo'",
            code=EXIT_INVALID_ARGS,
        )

    kind = data.get("kind")
    if not isinstance(kind, str):
        log.fatal(
            f"Lockfile {path}: package '{name}' missing 'kind'",
            code=EXIT_INVALID_ARGS,
        )

    ref_kind_str = data.get("ref-kind")
    if not isinstance(ref_kind_str, str):
        log.fatal(
            f"Lockfile {path}: package '{name}' missing 'ref-kind'",
            code=EXIT_INVALID_ARGS,
        )
    try:
        ref_kind = RefKind(ref_kind_str)
    except ValueError:
        log.fatal(
            f"Lockfile {path}: package '{name}' has invalid ref-kind '{ref_kind_str}'",
            code=EXIT_INVALID_ARGS,
        )

    ref_value = data.get("ref-value")
    if ref_value is None:
        log.fatal(
            f"Lockfile {path}: package '{name}' missing 'ref-value'",
            code=EXIT_INVALID_ARGS,
        )
    if not isinstance(ref_value, (str, int)):
        log.fatal(
            f"Lockfile {path}: package '{name}' 'ref-value' must be string or int",
            code=EXIT_INVALID_ARGS,
        )

    resolved_tag = data.get("resolved-tag")
    if not isinstance(resolved_tag, str):
        log.fatal(
            f"Lockfile {path}: package '{name}' missing 'resolved-tag'",
            code=EXIT_INVALID_ARGS,
        )

    resolved_commitish = data.get("resolved-commitish")
    if not isinstance(resolved_commitish, str):
        log.fatal(
            f"Lockfile {path}: package '{name}' missing 'resolved-commitish'",
            code=EXIT_INVALID_ARGS,
        )

    release_id = data.get("release-id")
    if not isinstance(release_id, int):
        log.fatal(
            f"Lockfile {path}: package '{name}' missing or invalid 'release-id'",
            code=EXIT_INVALID_ARGS,
        )

    raw_deps = data.get("dependencies", [])
    if not isinstance(raw_deps, list):
        log.fatal(
            f"Lockfile {path}: package '{name}' 'dependencies' must be a list",
            code=EXIT_INVALID_ARGS,
        )
    dependencies: list[str] = [str(d) for d in cast("list[object]", raw_deps)]

    transitive = data.get("transitive", False)
    if not isinstance(transitive, bool):
        log.fatal(
            f"Lockfile {path}: package '{name}' 'transitive' must be a boolean",
            code=EXIT_INVALID_ARGS,
        )

    raw_required_by = data.get("required-by", [])
    if not isinstance(raw_required_by, list):
        log.fatal(
            f"Lockfile {path}: package '{name}' 'required-by' must be a list",
            code=EXIT_INVALID_ARGS,
        )
    required_by: list[str] = [str(r) for r in cast("list[object]", raw_required_by)]

    # Parse assets
    raw_assets = data.get("assets", [])
    if not isinstance(raw_assets, list):
        log.fatal(
            f"Lockfile {path}: package '{name}' 'assets' must be a list",
            code=EXIT_INVALID_ARGS,
        )

    assets: list[ResolvedAsset] = []
    for raw_asset_item in cast("list[object]", raw_assets):
        if not isinstance(raw_asset_item, dict):
            log.fatal(
                f"Lockfile {path}: package '{name}' asset must be a table",
                code=EXIT_INVALID_ARGS,
            )
        asset_data = cast("dict[str, object]", raw_asset_item)
        a_name = asset_data.get("name")
        a_url = asset_data.get("url")
        if not isinstance(a_name, str) or not isinstance(a_url, str):
            log.fatal(
                f"Lockfile {path}: package '{name}' asset missing 'name' or 'url'",
                code=EXIT_INVALID_ARGS,
            )
        assets.append(ResolvedAsset(name=a_name, url=a_url))

    return ResolvedPackage(
        name=name,
        repo=repo,
        kind=kind,
        ref=Ref(kind=ref_kind, value=ref_value),
        resolved_tag=resolved_tag,
        resolved_commitish=resolved_commitish,
        release_id=release_id,
        dependencies=dependencies,
        assets=assets,
        transitive=transitive,
        required_by=required_by,
    )


# ---------------------------------------------------------------------------
# Release asset download
# ---------------------------------------------------------------------------


def download_lockfile_asset(
    release: dict[str, object],
    dest: Path,
    gh_token: str | None = None,
) -> Lockfile | None:
    """Download a ``nanvix.lock`` asset from a GitHub release.

    Searches the release's ``assets`` list for one named ``nanvix.lock``.
    If found, downloads it to *dest*, parses it, and returns the
    :class:`Lockfile`.  Returns ``None`` if no such asset exists
    (leaf package with no dependencies).

    Args:
        release: GitHub release metadata dictionary (from the API).
        dest: Directory where the downloaded file will be saved.
        gh_token: Optional GitHub personal access token.

    Returns:
        The parsed :class:`Lockfile`, or ``None`` if the release has no
        ``nanvix.lock`` asset.
    """
    raw_assets: object = release.get("assets", [])
    if not isinstance(raw_assets, list):
        return None

    download_url: str | None = None
    for asset_item in cast("list[object]", raw_assets):
        if not isinstance(asset_item, dict):
            continue
        asset = cast("dict[str, object]", asset_item)
        name = asset.get("name")
        if name == _LOCKFILE_ASSET_NAME:
            raw_url = asset.get("browser_download_url")
            if isinstance(raw_url, str) and raw_url:
                download_url = raw_url
            break

    if download_url is None:
        return None

    dest.mkdir(parents=True, exist_ok=True)
    out_path = dest / _LOCKFILE_ASSET_NAME

    headers: dict[str, str] = {"Accept": "application/octet-stream"}
    if gh_token:
        headers["Authorization"] = f"Bearer {gh_token}"

    for attempt in range(1, _MAX_RETRIES + 1):
        try:
            req = urllib.request.Request(download_url, headers=headers)
            with (
                urllib.request.urlopen(req, timeout=_HTTP_TIMEOUT) as resp,
                out_path.open("wb") as out_fh,
            ):
                while True:
                    chunk = resp.read(1024 * 1024)
                    if not chunk:
                        break
                    out_fh.write(chunk)
            return read_lockfile(out_path)
        except urllib.error.URLError as exc:
            if attempt == _MAX_RETRIES:
                log.fatal(
                    f"Failed to download lockfile asset: {exc}",
                    code=EXIT_NETWORK_ERROR,
                    hint="Check your network connection or set GH_TOKEN.",
                )
            wait = _BACKOFF_BASE**attempt
            log.warning(f"Download attempt {attempt} failed; retrying in {wait:.0f}s…")
            time.sleep(wait)

    return None  # pragma: no cover


# ---------------------------------------------------------------------------
# Manifest hash
# ---------------------------------------------------------------------------


def compute_manifest_hash(path: Path) -> str:
    """Compute the SHA-256 hash of a manifest file.

    Reads the raw bytes of the file and returns the hash as
    ``"sha256:<hex>"``.

    Args:
        path: Path to the ``nanvix.toml`` file.

    Returns:
        Hash string in the format ``"sha256:<hex>"``.
    """
    if not path.is_file():
        log.fatal(
            f"Manifest not found: {path}",
            code=EXIT_MISSING_DEP,
            hint="Ensure nanvix.toml exists in .nanvix/.",
        )
    raw_bytes = path.read_bytes()
    digest = hashlib.sha256(raw_bytes).hexdigest()
    return f"sha256:{digest}"
