# Copyright(c) The Maintainers of Nanvix.
# Licensed under the MIT License.

"""Lockfile data model, serialization, and release-asset download.

Defines the ``Lockfile`` dataclass that captures the fully resolved
dependency graph with pinned asset URLs.  Provides ``write_lockfile()``
to serialize a lockfile to TOML and ``read_lockfile()`` to parse it back.
``download_lockfile_asset()`` fetches a shallow ``nanvix.lock`` from a
GitHub release for transitive dependency discovery.
"""

from __future__ import annotations

import hashlib
import importlib.metadata
import tomllib
from dataclasses import dataclass, field
from pathlib import Path
from typing import cast

import tomli_w

from nanvix_zutil import github, log
from nanvix_zutil.buildroot import Ref, RefKind
from nanvix_zutil.exitcodes import (
    EXIT_INVALID_ARGS,
    EXIT_MISSING_DEP,
)
from nanvix_zutil.sdk import SdkImage, SdkProvenance

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

_LOCKFILE_HEADER = "# nanvix.lock - auto-generated by nanvix_zutil. DO NOT EDIT."
_LOCKFILE_ASSET_NAME = "nanvix.lock"


# ---------------------------------------------------------------------------
# Data model
# ---------------------------------------------------------------------------


@dataclass
class ResolvedAsset:
    """A single downloadable release artifact.

    Attributes:
        name: File name of the asset
            (e.g. ``"zlib-microvm-standalone-256mb.tar.bz2"``).
        url: Full ``browser_download_url`` from the GitHub API.
    """

    name: str
    url: str
    asset_id: int | None = None


@dataclass
class ResolvedPackage:
    """A fully resolved dependency in the lockfile.

    Attributes:
        name: Short package name (e.g. ``"zlib"``).
        repo: GitHub repository in ``owner/name`` format.
        kind: Either ``"sysroot"`` or ``"dependency"``.
        ref: The original version reference from the manifest.
        resolved_tag: Actual ``tag_name`` from the resolved release.
        resolved_commitish: Raw ``target_commitish`` from the release — may be a
            full SHA, branch name, or tag name.
        release_id: GitHub release ID.
        dependencies: Names of packages this package depends on.
        assets: List of downloadable archive assets.
        transitive: ``True`` if this package was discovered transitively.
        required_by: Names of packages that pulled this one in.
    """

    name: str
    repo: str
    kind: str
    ref: Ref
    resolved_tag: str
    resolved_commitish: str
    release_id: int
    dependencies: list[str] = field(default_factory=lambda: list[str]())
    assets: list[ResolvedAsset] = field(default_factory=lambda: list[ResolvedAsset]())
    transitive: bool = False
    required_by: list[str] = field(default_factory=lambda: list[str]())


@dataclass
class LockfileMetadata:
    """Lockfile header metadata.

    Attributes:
        manifest_hash: SHA-256 hash of the ``nanvix.toml`` file
            (e.g. ``"sha256:a1b2c3d4..."``).
        nanvix_zutil_version: Version of ``nanvix-zutil`` that
            generated this lockfile.
        sdk: Verified SDK provenance, or ``None`` for a legacy lock.
        shallow: Whether transitive dependency discovery was intentionally
            omitted when this lock was generated.
    """

    manifest_hash: str
    nanvix_zutil_version: str
    sdk: SdkProvenance | None = None
    shallow: bool = False


@dataclass
class Lockfile:
    """Complete resolved dependency graph.

    Attributes:
        metadata: Lockfile header metadata.
        packages: Ordered list of resolved packages.
    """

    metadata: LockfileMetadata
    packages: list[ResolvedPackage] = field(
        default_factory=lambda: list[ResolvedPackage]()
    )


# ---------------------------------------------------------------------------
# Version helper
# ---------------------------------------------------------------------------


def get_zutil_version() -> str:
    """Return the installed ``nanvix-zutil`` version string.

    Returns:
        Version string (e.g. ``"0.2.2"``), or ``"unknown"`` if the
        package metadata is unavailable.
    """
    try:
        return importlib.metadata.version("nanvix-zutil")
    except importlib.metadata.PackageNotFoundError:
        return "unknown"


# ---------------------------------------------------------------------------
# Write
# ---------------------------------------------------------------------------


def serialize_lockfile(lockfile: Lockfile) -> bytes:
    """Serialize a :class:`Lockfile` to canonical UTF-8 TOML bytes.

    The output starts with the standard lockfile header comment and
    includes a blank line before each ``[[package]]`` block for
    readability.

    Args:
        lockfile: The lockfile to serialize.
    Returns:
        Canonical lockfile bytes with LF line endings.
    """
    lines: list[str] = [_LOCKFILE_HEADER, ""]

    # [metadata]
    meta_dict: dict[str, object] = {
        "manifest-hash": lockfile.metadata.manifest_hash,
        "nanvix-zutil-version": lockfile.metadata.nanvix_zutil_version,
    }
    if lockfile.metadata.shallow:
        meta_dict["shallow"] = True
    lines.append(tomli_w.dumps({"metadata": meta_dict}).rstrip())
    if lockfile.metadata.sdk is not None:
        sdk = lockfile.metadata.sdk
        sdk_dict: dict[str, object] = {
            "schema-version": sdk.schema_version,
            "sdk-version": sdk.sdk_version,
            "provider-id": sdk.provider_id,
            "provider": sdk.provider,
            "role": sdk.role,
            "image-name": sdk.image.name,
            "image-digest": sdk.image.digest,
            "image-ref": sdk.image.ref,
            "nanvix-tag": sdk.nanvix_tag,
            "nanvix-version": sdk.nanvix_version,
            "nanvix-commit": sdk.nanvix_commit,
            "sysroot-sha256": sdk.sysroot_sha256,
        }
        lines.append("")
        lines.append("[metadata.sdk]")
        lines.append(tomli_w.dumps(sdk_dict).rstrip())
        for name, values in (
            ("target", sdk.target),
            ("toolchain", sdk.toolchain),
            ("compat", sdk.compat),
            ("features", sdk.features),
        ):
            lines.append("")
            lines.append(f"[metadata.sdk.{name}]")
            lines.append(tomli_w.dumps(values).rstrip())
    lines.append("")

    # [[package]] blocks
    for pkg in lockfile.packages:
        pkg_dict: dict[str, object] = {
            "name": pkg.name,
            "repo": pkg.repo,
            "kind": pkg.kind,
            "ref-kind": pkg.ref.kind.value,
            "ref-value": pkg.ref.value,
            "resolved-tag": pkg.resolved_tag,
            "resolved-commitish": pkg.resolved_commitish,
            "release-id": pkg.release_id,
            "dependencies": pkg.dependencies,
        }
        if pkg.transitive:
            pkg_dict["transitive"] = True
        if pkg.required_by:
            pkg_dict["required-by"] = pkg.required_by

        # Build assets as list of inline tables
        asset_dicts: list[dict[str, str]] = [
            {"name": a.name, "url": a.url} for a in pkg.assets
        ]

        lines.append("")
        lines.append("[[package]]")
        # Serialize the scalar fields
        for key, value in pkg_dict.items():
            lines.append(tomli_w.dumps({key: value}).rstrip())

        # Serialize assets as [[package.assets]] sub-tables
        for index, asset_dict in enumerate(asset_dicts):
            lines.append("")
            lines.append("[[package.assets]]")
            lines.append(tomli_w.dumps({"name": asset_dict["name"]}).rstrip())
            lines.append(tomli_w.dumps({"url": asset_dict["url"]}).rstrip())
            asset_id = pkg.assets[index].asset_id
            if asset_id is not None:
                lines.append(tomli_w.dumps({"id": asset_id}).rstrip())

    lines.append("")
    return "\n".join(lines).encode("utf-8")


def write_lockfile(lockfile: Lockfile, path: Path) -> None:
    """Serialize a :class:`Lockfile` and write it to *path*.

    Args:
        lockfile: The lockfile to serialize.
        path: Destination file path.
    """
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(serialize_lockfile(lockfile))


# ---------------------------------------------------------------------------
# Read
# ---------------------------------------------------------------------------


def read_lockfile(path: Path) -> Lockfile:
    """Parse a TOML lockfile into a :class:`Lockfile` dataclass.

    Args:
        path: Path to the ``nanvix.lock`` file.

    Returns:
        The parsed :class:`Lockfile`.

    Raises:
        SystemExit: With exit code ``3`` if the file does not exist, or
            exit code ``2`` if the file is malformed.
    """
    if not path.is_file():
        log.fatal(
            f"Lockfile not found: {path}",
            code=EXIT_MISSING_DEP,
            hint="Run `./z lock` to generate a lockfile.",
        )

    raw_bytes = path.read_bytes()
    try:
        data: dict[str, object] = tomllib.loads(raw_bytes.decode("utf-8"))
    except tomllib.TOMLDecodeError as exc:
        log.fatal(
            f"Malformed lockfile {path}: {exc}",
            code=EXIT_INVALID_ARGS,
        )

    # Parse metadata
    raw_meta: object = data.get("metadata")
    if not isinstance(raw_meta, dict):
        log.fatal(
            f"Lockfile {path}: missing or invalid [metadata] section",
            code=EXIT_INVALID_ARGS,
        )
    meta = cast("dict[str, object]", raw_meta)

    manifest_hash = meta.get("manifest-hash")
    if not isinstance(manifest_hash, str):
        log.fatal(
            f"Lockfile {path}: missing or invalid 'manifest-hash'",
            code=EXIT_INVALID_ARGS,
        )

    zutil_version = meta.get("nanvix-zutil-version")
    if not isinstance(zutil_version, str):
        log.fatal(
            f"Lockfile {path}: missing or invalid 'nanvix-zutil-version'",
            code=EXIT_INVALID_ARGS,
        )

    shallow_value = meta.get("shallow", False)
    # Transitional writer 0.15.0 accidentally emitted shallow as a string;
    # accept it when reading while all new writes use a TOML boolean.
    if shallow_value == "true":
        shallow_value = True
    if not isinstance(shallow_value, bool):
        log.fatal(
            f"Lockfile {path}: invalid metadata 'shallow'",
            code=EXIT_INVALID_ARGS,
        )
    raw_sdk = meta.get("sdk")
    sdk = (
        _parse_sdk_provenance(cast("dict[str, object]", raw_sdk), path)
        if isinstance(raw_sdk, dict)
        else None
    )
    if raw_sdk is not None and sdk is None:
        log.fatal(
            f"Lockfile {path}: metadata.sdk must be a table",
            code=EXIT_INVALID_ARGS,
        )

    metadata = LockfileMetadata(
        manifest_hash=manifest_hash,
        nanvix_zutil_version=zutil_version,
        sdk=sdk,
        shallow=shallow_value,
    )

    # Parse packages
    raw_packages: object = data.get("package", [])
    if not isinstance(raw_packages, list):
        log.fatal(
            f"Lockfile {path}: 'package' must be an array of tables",
            code=EXIT_INVALID_ARGS,
        )

    packages: list[ResolvedPackage] = []
    for raw_pkg_item in cast("list[object]", raw_packages):
        if not isinstance(raw_pkg_item, dict):
            log.fatal(
                f"Lockfile {path}: each [[package]] must be a table",
                code=EXIT_INVALID_ARGS,
            )
        pkg_data = cast("dict[str, object]", raw_pkg_item)
        packages.append(_parse_package(pkg_data, path))

    return Lockfile(metadata=metadata, packages=packages)


def _parse_sdk_provenance(
    data: dict[str, object],
    path: Path,
) -> SdkProvenance:
    """Parse verified SDK provenance from lockfile metadata."""

    def text(key: str) -> str:
        value = data.get(key)
        if not isinstance(value, str) or not value:
            log.fatal(
                f"Lockfile {path}: metadata.sdk missing or invalid {key!r}",
                code=EXIT_INVALID_ARGS,
            )
        return value

    def object_table(key: str, *, required: bool = False) -> dict[str, object]:
        value = data.get(key)
        if value is None and not required:
            return {}
        if not isinstance(value, dict):
            log.fatal(
                f"Lockfile {path}: metadata.sdk {key!r} must be a table",
                code=EXIT_INVALID_ARGS,
            )
        return dict(cast("dict[str, object]", value))

    raw_compat = object_table("compat", required=True)
    schema_version = data.get("schema-version", 1)
    if (
        not isinstance(schema_version, int)
        or isinstance(schema_version, bool)
        or schema_version != 1
    ):
        log.fatal(
            f"Lockfile {path}: unsupported metadata.sdk schema-version",
            code=EXIT_INVALID_ARGS,
        )
    image = SdkImage(
        name=text("image-name"),
        digest=text("image-digest"),
        ref=text("image-ref"),
    )
    if image.ref != f"{image.name}@{image.digest}":
        log.fatal(
            f"Lockfile {path}: metadata.sdk image coordinate is inconsistent",
            code=EXIT_INVALID_ARGS,
        )
    return SdkProvenance(
        sdk_version=text("sdk-version"),
        provider_id=text("provider-id"),
        provider=text("provider"),
        role=text("role"),
        image=image,
        nanvix_tag=text("nanvix-tag"),
        nanvix_version=text("nanvix-version"),
        nanvix_commit=text("nanvix-commit"),
        sysroot_sha256=text("sysroot-sha256"),
        compat=raw_compat,
        schema_version=1,
        target=object_table("target"),
        toolchain=object_table("toolchain"),
        features=object_table("features"),
    )


def _parse_package(data: dict[str, object], path: Path) -> ResolvedPackage:
    """Parse a single ``[[package]]`` entry.

    Args:
        data: The parsed TOML table for one package.
        path: Lockfile path (for error messages).

    Returns:
        A :class:`ResolvedPackage`.
    """
    name = data.get("name")
    if not isinstance(name, str):
        log.fatal(f"Lockfile {path}: package missing 'name'", code=EXIT_INVALID_ARGS)

    repo = data.get("repo")
    if not isinstance(repo, str):
        log.fatal(
            f"Lockfile {path}: package '{name}' missing 'repo'",
            code=EXIT_INVALID_ARGS,
        )

    kind = data.get("kind")
    if not isinstance(kind, str):
        log.fatal(
            f"Lockfile {path}: package '{name}' missing 'kind'",
            code=EXIT_INVALID_ARGS,
        )

    ref_kind_str = data.get("ref-kind")
    if not isinstance(ref_kind_str, str):
        log.fatal(
            f"Lockfile {path}: package '{name}' missing 'ref-kind'",
            code=EXIT_INVALID_ARGS,
        )
    try:
        ref_kind = RefKind(ref_kind_str)
    except ValueError:
        log.fatal(
            f"Lockfile {path}: package '{name}' has invalid ref-kind '{ref_kind_str}'",
            code=EXIT_INVALID_ARGS,
        )

    ref_value = data.get("ref-value")
    if ref_value is None:
        log.fatal(
            f"Lockfile {path}: package '{name}' missing 'ref-value'",
            code=EXIT_INVALID_ARGS,
        )
    if not isinstance(ref_value, (str, int)):
        log.fatal(
            f"Lockfile {path}: package '{name}' 'ref-value' must be string or int",
            code=EXIT_INVALID_ARGS,
        )

    resolved_tag = data.get("resolved-tag")
    if not isinstance(resolved_tag, str):
        log.fatal(
            f"Lockfile {path}: package '{name}' missing 'resolved-tag'",
            code=EXIT_INVALID_ARGS,
        )

    resolved_commitish = data.get("resolved-commitish")
    if not isinstance(resolved_commitish, str):
        log.fatal(
            f"Lockfile {path}: package '{name}' missing 'resolved-commitish'",
            code=EXIT_INVALID_ARGS,
        )

    release_id = data.get("release-id")
    if not isinstance(release_id, int):
        log.fatal(
            f"Lockfile {path}: package '{name}' missing or invalid 'release-id'",
            code=EXIT_INVALID_ARGS,
        )

    raw_deps = data.get("dependencies", [])
    if not isinstance(raw_deps, list):
        log.fatal(
            f"Lockfile {path}: package '{name}' 'dependencies' must be a list",
            code=EXIT_INVALID_ARGS,
        )
    dependencies: list[str] = [str(d) for d in cast("list[object]", raw_deps)]

    transitive = data.get("transitive", False)
    if not isinstance(transitive, bool):
        log.fatal(
            f"Lockfile {path}: package '{name}' 'transitive' must be a boolean",
            code=EXIT_INVALID_ARGS,
        )

    raw_required_by = data.get("required-by", [])
    if not isinstance(raw_required_by, list):
        log.fatal(
            f"Lockfile {path}: package '{name}' 'required-by' must be a list",
            code=EXIT_INVALID_ARGS,
        )
    required_by: list[str] = [str(r) for r in cast("list[object]", raw_required_by)]

    # Parse assets
    raw_assets = data.get("assets", [])
    if not isinstance(raw_assets, list):
        log.fatal(
            f"Lockfile {path}: package '{name}' 'assets' must be a list",
            code=EXIT_INVALID_ARGS,
        )

    assets: list[ResolvedAsset] = []
    for raw_asset_item in cast("list[object]", raw_assets):
        if not isinstance(raw_asset_item, dict):
            log.fatal(
                f"Lockfile {path}: package '{name}' asset must be a table",
                code=EXIT_INVALID_ARGS,
            )
        asset_data = cast("dict[str, object]", raw_asset_item)
        a_name = asset_data.get("name")
        a_url = asset_data.get("url")
        a_id = asset_data.get("id")
        if not isinstance(a_name, str) or not isinstance(a_url, str):
            log.fatal(
                f"Lockfile {path}: package '{name}' asset missing 'name' or 'url'",
                code=EXIT_INVALID_ARGS,
            )
        if a_id is not None and not isinstance(a_id, int):
            log.fatal(
                f"Lockfile {path}: package '{name}' asset id must be an integer",
                code=EXIT_INVALID_ARGS,
            )
        assets.append(ResolvedAsset(name=a_name, url=a_url, asset_id=a_id))

    return ResolvedPackage(
        name=name,
        repo=repo,
        kind=kind,
        ref=Ref(kind=ref_kind, value=ref_value),
        resolved_tag=resolved_tag,
        resolved_commitish=resolved_commitish,
        release_id=release_id,
        dependencies=dependencies,
        assets=assets,
        transitive=transitive,
        required_by=required_by,
    )


# ---------------------------------------------------------------------------
# Release asset download
# ---------------------------------------------------------------------------


def download_lockfile_asset(
    release: dict[str, object],
    dest: Path,
    gh_token: str | None = None,
    *,
    dep_name: str = "",
) -> Lockfile | None:
    """Download a ``nanvix.lock`` asset from a GitHub release.

    Delegates to :func:`github.download_release_asset` for the actual
    HTTP download (retry, backoff, auth).  Returns ``None`` if the
    release has no ``nanvix.lock`` asset (leaf package).

    Each dependency's lockfile is saved in a per-dependency subdirectory
    of *dest* (``dest / dep_name``) so that concurrent resolutions for
    different packages do not share a cache entry.

    Args:
        release: GitHub release metadata dictionary (from the API).
        dest: Base directory where downloaded files will be saved.
        gh_token: Optional GitHub personal access token.
        dep_name: Short name of the dependency (used for the
            per-dependency subdirectory and log context).

    Returns:
        The parsed :class:`Lockfile`, or ``None`` if the release has no
        ``nanvix.lock`` asset.
    """
    raw_assets: object = release.get("assets", [])
    if not isinstance(raw_assets, list):
        return None

    has_lockfile = any(
        isinstance(a, dict)
        and cast("dict[str, object]", a).get("name") == _LOCKFILE_ASSET_NAME
        for a in cast("list[object]", raw_assets)
    )
    if not has_lockfile:
        return None

    # Use a per-dependency subdirectory to avoid cache collisions when
    # multiple dependencies each ship a nanvix.lock asset.
    sub_dest = dest / dep_name if dep_name else dest

    # Extract tag from the release for meaningful log context.
    tag_name: object = release.get("tag_name", "")
    version_specifier: str | int = tag_name if isinstance(tag_name, str) else ""

    asset_path = github.download_release_asset(
        repo="",
        version_specifier=version_specifier,
        asset_name=_LOCKFILE_ASSET_NAME,
        dest=sub_dest,
        gh_token=gh_token,
        _release=release,
        allow_missing=True,
    )
    if asset_path is None:
        return None

    return read_lockfile(asset_path)


# ---------------------------------------------------------------------------
# Manifest hash
# ---------------------------------------------------------------------------


def compute_manifest_hash(path: Path) -> str:
    """Compute the SHA-256 hash of a manifest file.

    Reads the raw bytes of the file, normalizes CRLF to LF for
    cross-platform determinism, and returns the hash as
    ``"sha256:<hex>"``.

    Args:
        path: Path to the ``nanvix.toml`` file.

    Returns:
        Hash string in the format ``"sha256:<hex>"``.
    """
    if not path.is_file():
        log.fatal(
            f"Manifest not found: {path}",
            code=EXIT_MISSING_DEP,
            hint="Ensure nanvix.toml exists in .nanvix/.",
        )
    return compute_manifest_hash_bytes(path.read_bytes())


def compute_manifest_hash_bytes(raw_bytes: bytes) -> str:
    """Compute the normalized manifest hash from in-memory bytes."""
    raw_bytes = raw_bytes.replace(b"\r\n", b"\n")
    digest = hashlib.sha256(raw_bytes).hexdigest()
    return f"sha256:{digest}"
